project_id = "upoxlymldxmhjttktylu"

[functions.process-document]
verify_jwt = false

[functions.transcribe-voice]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.generate-social-content]
verify_jwt = false

[functions.generate-flyer-image]
verify_jwt = false

[functions.publish-scheduled-posts]
verify_jwt = false

[functions.generate-resume]
verify_jwt = false

[functions.parse-cv]
verify_jwt = false

[functions.create-backup]
verify_jwt = false

[functions.restore-backup]
verify_jwt = false

[functions.scheduled-backup]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false
